name: hola

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."