name: hola

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: List files
        run: |
          ls -all

      - name: touch file
        run: |
          touch test.txt

      - name: Set text
        run: |
          echo "Hello World" > test.txt

  other-job:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: LS 
        run: ls -all